# =========================================================
# BANCO DE DADOS H2
# =========================================================

# Banco salvo em arquivo dentro da pasta data do projeto.
spring.datasource.url=jdbc:h2:file:./data/futebol-db

# Driver JDBC do H2.
spring.datasource.driver-class-name=org.h2.Driver

# Usuario e senha.
spring.datasource.username=sa
spring.datasource.password=


# =========================================================
# JPA / HIBERNATE
# =========================================================

# Cria e atualiza as tabelas automaticamente.
spring.jpa.hibernate.ddl-auto=update

# Nao mostra todos os comandos SQL no console.
spring.jpa.show-sql=false


# =========================================================
# CONSOLE H2
# =========================================================

# Habilita o console web do banco.
spring.h2.console.enabled=true

# Endereco do console.
spring.h2.console.path=/h2-console

debug=true
